export const GET_ARTIST_DETAILS = 'GET_ARTIST_DETAILS';
export const ARTIST_NAME = 'ARTIST_NAME';
export const ARTIST_IMAGE = 'ARTIST_IMAGE';
export const ARTIST_ABOUT = 'ARTIST_ABOUT';
export const NAVIGATION_BUTTON_SELECT = 'NAVIGATION_BUTTON_SELECT';
export const ARTIST_TRACKS = 'ARTIST_TRACKS';
